<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@include file="./header.jsp" %>

	<div class="container">
		<p /> 
		<h2>Gizlilik Politikası</h2>
		

		<p />KriptoRobo, gizliliğinizi korumak ve kullanılmakta bulunan teknolojik altyapıdan en üst seviyede yararlanmanızı sağlayabilmek amacıyla; kişisel bilgi ve veri güvenliğiniz için çeşitli gizlilik ilkeleri benimsemiştir. Bu gizlilik ilkeleri dahilinde KriptoRobo internet sitesi ve tüm alt internet sitelerinde veri toplanması ve/veya kullanımı konusunda uygulanmak üzere belirlenmiş ve beyan edilmektedir.
		 
		<p />KriptoRobo internet sitesini ziyaret etmekle ve/veya kullanmakla ve/veya üye olmakla belirtilen bu ilkelerin tümü Kullanıcı tarafından kabul edilmiş sayılır. KriptoRobo sayfasında belirtilen iletişim adreslerinden birisi ile kendisine yapılacak geri bildirimler doğrultusunda, “Gizlilik Bildirimi” bölümünde düzeltme ve güncelleme gibi işlemleri, önceden bildirmeksizin her zaman yapabilir. KriptoRobo “Gizlilik Bildirimi” bölümünü belli aralıklarla güncelleyebilir ve kullanıcı belli aralıklarla bu bölümü ziyaret ederek yeni gelişmelerden haberdar olabilir.
		 
		<p />KriptoRobo, ziyaretçileri ya da kullanıcıları tarafından web sitesi üzerinden kendisine elektronik ortamdan iletilen her türden kişisel bilgileri ve verileri üçüncü kişilere hiç bir şekilde açıklamayacaktır. KriptoRobo, sunmuş olduğu hizmetlerin ve servislerin daha efektif kullanılabilmesi amacıyla bir çok 3. Parti kurum ve kuruluşlarla çeşitli şekillerde işbirliği yapabilir. Bu işbirliği; reklam, sponsorluk, izinli pazarlama, veri paylaşımı ve yasal diğer ticari yöntemlerle olabilir. KriptoRobo, iletişim faaliyetlerinde, kanunların öngördüğü şekilde izinli iletişim / pazarlama yapacağını, kullanıcının isteği dışında iletişim yapmamayı, kullanıcının sistemden ücretsiz ve kolayca çıkabilmesini sağlayacak araçlar sunmayı beyan ve taahhüt eder. KriptoRobo, kendisine iletilen kişisel verileri ve bilgileri, bilgilerin toplanması ile ilgili açıklanan yukarıdaki amaçlar dışında üçüncü kişilerle kesinlikle paylaşmayacak, satışını yapmayacak ve hiç bir şart altında kullanılmasına izin vermeyecektir.
		 
		<p />Sitedeki sistemle ilgili sorunların tanımlanabilmesi ve KriptoRobo sitesinde çıkabilecek muhtemel sorunların acil olarak giderilmesi için, KriptoRobo gerektiğinde kullanıcıların IP adresini kaydedebilir ve bu kayıtları anılan bu amaçlarla kullanabilir. Bu IP adresleri, KriptoRobo tarafından kullanıcılarını ve ziyaretçilerini genel anlamda tanımlamak ve kapsamlı şekilde demografik veri toplayabilmek amacıyla kullanılabilir. KriptoRobo sitesinin 5651 sayılı yasada belirtilen trafik verisi saklama yükümlülükleri ayrıca saklıdır.
		 
		<p />KriptoRobo’a kayıt olarak üye sıfatının kazanılması için veya üye olmaksızın çeşitli servis ve içeriklerden faydalanabilmesi için, ziyaretçilerin kendileriyle ilgili bir takım kişisel bilgilerini (örnek olarak: isim ve soy isim, telefon numarası, posta adresi, e-posta adresi vb.) formlar aracılığıyla KriptoRobo’e vermeleri gerekmektedir. KriptoRobo’ın, kayıt sırasında talep edebileceği bu bilgiler sistemde kayıtlı olarak tutulabilir. İletilen bu kişisel bilgiler, gerektiğinde kullanıcılarla iletişime geçmek amacıyla da kullanılabilir. KriptoRobo tarafından talep edilebilecek bilgiler veya kullanıcı tarafından aktarılan bilgiler veya Site üzerinden yapılan işlemlerde ortaya koyulan ilgili bilgiler KriptoRobo ve işbirliği içinde olduğu diğer kişi ve kurumlar tarafından kullanıcının kimliği hiç bir şekilde açığa çıkarılmaksızın sadece çeşitli istatistiki değerlendirmeler, izinli iletişim ve pazarlama, veri tabanı oluşturma çabaları ve pazar araştırmaları yapma gibi durumlar dahilinde kullanılabilir.
		 
		<p />KriptoRobo, Site içerisinde başkaca sitelere link(bağlantı) sağlayabilir. Anlaşmalı olduğu 3. Partilerin reklamlarını ve/veya çeşitli hizmetlere ilişkin başvuru formlarını yayınlayabilir, Kullanıcıları bu formlar ve reklamlar aracılığıyla reklamveren veya anlaşmalı 3. partilerin sitesine yönlendirebilir. KriptoRobo, bu bağlantı yoluyla erişilen diğer sitelerin gizlilik uygulama ve politikalarına ya da barındırdıkları içeriklere yönelik olmak üzere hiç bir sorumluluk taşımamaktadır.
		 
		<p />Kullanıcıya ait kişisel bilgiler, ad ve soy ad, adres, telefon numarası, elektronik posta adresi ve kullanıcıyı tanımlamaya yönelik diğer her türlü bilgi olarak anlaşılır. KriptoRobo, işbu gizlilik bildiriminde aksi belirtilmedikçe kişisel bilgilerden herhangi birini KriptoRobo’ın işbirliği içinde olmadığı şirketlere ve üçüncü kişilere hiç bir şekilde açıklamayacaktır. KriptoRobo, aşağıda sayılan hallerde ise işbu gizlilik bildirimi hükümleri dışına çıkarak kullanıcılara ait bilgileri üçüncü kişilere açıklayabilecektir. Bu durumlar;Kanun, KHK, Yönetmelik vb. yetkili hukuki makamlar tarafından çıkarılan ve yürürlükte bulunan hukuk kurallarının getirdiği zorunluluklara uyulmasının gerektiği haller,KriptoRobo’ın kullanıcılarıyla arasındaki sözleşmelerin gereklerinin yerine getirilmesi ve bunların uygulamaya konulmalarıyla ilgili hallerde, Yetkili idari ve/veya adli makamlar tarafından usuli yöntemine uygun olarak yürütülen bir araştırma veya soruşturma doğrultusunda kullanıcılarla ilgili bilgi talep edilmesi hallerinde,Kullanıcıların haklarını veya güvenliklerini koruma amacıyla bilgi verilmesinin gerekli olduğu hallerde.
		 
		<p />KriptoRobo, kendisine verilen gizli bilgileri kesinlikle özel ve gizli tutmayı, bunu bir sır olarak saklamayı yükümlülük olarak kabul ettiğini ve gizliliğin sağlanıp sürdürülmesi, gizli bilginin tamamının veya herhangi bir parçasının kamu alanına girmesini veya yetkisiz kullanımını veya üçüncü bir kişiye açıklanmasını önleme gereği olan gerekli tüm tedbirleri almayı ve üzerine düşen tüm özeni tam olarak göstermeyi işbu bildirimle taahhüt etmektedir.
		 
		<p />KriptoRobo, kullanıcılar ve kullanıcıların KriptoRobo sitesi kullanımı hakkındaki bilgileri, teknik bir iletişim dosyası olan çerezler (Cookie) kullanarak elde edebilir. Bahsi geçen teknik iletişim dosyaları, ana bellekte saklanmak üzere bir internet sitesinin, kullanıcının tarayıcısına (browser) gönderdiği minik metin dosyalarından ibarettir. Teknik iletişim dosyası bir internet sitesi hakkında kullanıcının bilgisayarındaki ilgili durum ve basit tercih ayarlarını saklayarak internet kullanımını bu anlamda kolaylaştırır. Bu bahsedilen teknik iletişim dosyası, internet sitesini zamansal oranlamalı olarak kaç kişinin kullandığını, bir kişinin ilgili internet sitesini hangi amaçla, kaç kez ziyaret ettiği ve ne kadar kaldığı hakkında istatistiki bilgiler elde etmeye ve kullanıcılar için özel olarak tasarlanmış kullanıcı sayfalarından dinamik çeşitlilikle reklam ve içerik üretilmesine yardımcı olmak üzere tasarlanmış ve kullanılmaktadır. Teknik iletişim dosyası, ana bellekten başkaca herhangi bir kişisel bilgi almak için tasarlanmamıştır. Tarayıcıların pek çoğu kurulum aşamasında bu teknik iletişim dosyasını kabul eder biçimde hazırlanmışlardır, ancak kullanıcılar dilerlerse teknik iletişim dosyasının bilgisayarlarına yerleştirilmemesi veya bu türden bir dosyasının gönderildiğinde ikaz verilmesini sağlayacak biçimde tarayıcılarının ayarlarını her zaman değiştirebilirler.
		 
		<p />KriptoRobo tarafından Site içerisinde düzenlenebilecek periyodik veya periyodik olmayan anketlere cevap veren kullanıcılardan talep edilebilecek bilgiler de, KriptoRobo ve işbirliği içindeki kişi ya da kurumlar tarafından bu kullanıcılara doğrudan pazarlama yapmak, istatistiki analizler yapmak ve özel bir veri tabanı oluşturmak amacıyla da kullanılabilmektedir.
		 
		<p />KriptoRobo, işbu gizlilik bildiriminde geçen hükümleri gerekli gördüğü anlarda KriptoRobo sitesinde sayfasında yayınlamak şartıyla değiştirebilir. KriptoRobo’in değişiklik yaptığı gizlilik bildirimi hükümleri, ilgili sayfada yayınlandığı tarihte yürürlüğe girmiş kabul edilirle
		
		
		<p /><small>By using KriptoRobo, you accept these terms and conditions in full. If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this website.
		You understand and agree that we will not be liable or responsible for any loss or damage due to any reason. By using KriptoRobo, you acknowledge that you are familiar with these risks and that you are solely responsible for the outcomes of your decisions. We accept no liability whatsoever for any direct or consequential loss arising from the use of this product. You understand and agree that past results are not necessarily indicative of future performance.
		KriptoRobo does not take responsibility for the performance of external factors, like, for example, the availability of the Web servers, power failures or performance of the exchanges, on which we have no influence. Should financial or personal losses and/or financial damage ocurr due to such events, we cannot be held responsible for them. Despite careful research and throughtful supply of all the information, we are not responsible for any possible failure.
		The owner does not take responsibility for possible losses at exchange markets or other investments. We recommend to always test the trading system beforehand with small amounts, the Customer should decide whether the tradings system should trade for real.
		We take the protection of your data very seriously. Emails, names and all further personal information are absolutely confidentially treated by us and used only for internal purposes. Sharing your data to any other entieies is hereby excluded.
		Any account found to be associated with the delivery of spam or with any other illegal activities, will be immediately terminated without prior notice and with no refund.
		Any source code submitted by you will remain your intellectual property. However, any content, including source code, that was made public by you, cannot be removed by request and will remain publicly available. KriptoRobo won't access your strategies unless permission has been granted by you or it is required for maintenance.
		KriptoRobo reserves the right to update and change the Terms from time to time without notice. Any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Terms. Continued use of the website and/or guide after any such changes shall constitute your consent to such changes.</small>

		<p />
	</div>
	

<%@include file="./footer.jsp" %>		